docs/customcommands: document custom commands section
botlabs-gg/yagpdb-docs-v2 pull request #14
Opened 2024-02-29 02:14 UTC by SoggySaussages

- docs/customcommands: add custom-commands chapter
- docs/customcommands: document commands page

I plan on adding the database page and proofreading everything in full, but I'd appreciate feedback to know if I'm heading in the right direction. 

For your convenience I am hosting this branch on https://yagdocsv2.vedamaharaj.ca/custom-commands.html.

**Terms**
- [x] I have read and understood this project's [Contributing Guidelines](CONTRIBUTING.md)

2024-02-29 11:54 UTC, savage4618 commented on content/custom-commands/commands.md
> +It is reccomended to code your custom command using a local editor on your device. You will not be able to save your code on the dashboard if there are syntax errors in your code. Use an editor like
consider expanding `VSC` to `VS Code`

2024-02-29 11:57 UTC, savage4618 reviewed
I have a slight complaint about the images looking like they were grabbed from mobile. The more I think about it though, the more I think it might be fine with the amount of people asking about how to navigate the control panel via mobile.

2024-02-29 21:09 UTC, l-zeuch requested changes
You have a somewhat inconsistent use of title case in your headers.

I understand that this may cause inconsistencies with the control panel
due to them being labelled in "normal" case, but I think we should stick
to title case as long as said label isn't a full sentence or something
to that extend.

I.e. "Output errors as command response" stays as-is,
but "Saving your command" should be "Saving Your Command" instead.

2024-02-29 21:09 UTC, l-zeuch commented on content/custom-commands/commands.md
> +This is a relatively common trip-hazard, so take great care when you set up both whitelisted and blacklisted roles, and subsequently give those roles to your members.
This feels confusingly worded given how you note blacklisted channels
*and* blacklisted roles — I understand that you copied this from
botlabs-gg/yagpdb-docs-v2#13, but we might want to reword this to also
include the mention about roles, or be generic about a blacklist.

As a tangential note, command overrides as seen in core do not have
blacklisted channels, so this rewording does not exactly apply there.

2024-02-29 21:09 UTC, l-zeuch commented on content/custom-commands/commands.md
> +```
Should disallow :duck:. :stuck_out_tongue:

2024-03-03 09:15 UTC, l-zeuch commented
General note: As previously discussed in the private `#documentation`
channel, we now hold images *next* to the markdown files, rather than
having to mirror our content structure to `static/images/`.

If you have not done that already, please remember to do so.

2024-03-24 17:59 UTC, l-zeuch requested changes

2024-03-24 17:59 UTC, l-zeuch commented on .vscode/settings.json
Accidental check-out of this file?

I should probably add it to `.gitignore`...

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/_index.md
> +Custom Commands (CCs) allow you to develop your own commands and behaviours for your server. A command may be as simple as an autoresponder or employ a more complex system. A variety of triggers are
Remember to hard-break at 120 characters. Also, as much as it pains me,
too, we're using American English in this documentation.

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/commands.md
> +long as it isn't disabled and a channel is selected, and redirects you to the  edit command page for the command.
It seems like there are too many consecutive spaces here.
```suggestion
long as it isn't disabled and a channel is selected, and redirects you to the edit command page for the command.
```

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/commands.md
> +toggle (**5**) which is off by default. A case sensitive trigger `yagPDB` will trigger on "yagPDB" but not "yagpdb" or
The adjective is normally spelt "case-sensitive"; "Case sensitivity" as
seen on the control panel is also correct, however.

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/commands.md
> +The edited message toggle is an _additional_ trigger to the sent message trigger. If you'd like to _only_ trigger on
Personally, I would just call it a "normal message trigger", "sent
message trigger" feels quite confusing, especially when we take into
account what it is called on the control panel (no such thing).

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/commands.md
> +This feature is [premium only](/premium).
Not entirely sure if it might be worthwhile to move this one up a bit,
perhaps right underneath this very header?

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/commands.md
> +command fails. Does not effect logging of Last Error to the statistics.
```suggestion
command fails. Does not affect logging of Last Error to the statistics.
```

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/database.md
> +may seach for a specific ID using the **Search Bar** (**11**) with ID **Query** (**10**).
```suggestion
may search for a specific ID using the **Search Bar** (**11**) with ID **Query** (**10**).
```

2024-03-24 17:59 UTC, l-zeuch commented on content/custom-commands/database.md
> +Size of the value in bytes. YAGPDB database entries have a max value size of 100kB.
You generally have a (non-breaking) space between the numerical value
and the unit symbol, minus a very few exceptions like `°C`. My
professors also always chastize me when I do not do that, so I feel your
pain. :-)
```suggestion
Size of the value in bytes. YAGPDB database entries have a max value size of 100 kB.
```

2024-03-24 19:38 UTC, SoggySaussages commented on .vscode/settings.json
I swear I amended this commit like two or three times to get rid of this damn file, and yet >:(

2024-03-25 10:49 UTC, merged

2024-03-25 10:50 UTC, l-zeuch commented
I've gone ahead fixed the last two review comments myself.

Thanks for the PR!